---
  - name: 'Installing packages'
    ansible.builtin.apt:
      state: latest
      update_cache: yes
      pkg:
      - apache2
      - ghostscript
      - libapache2-mod-php
      - php
      - php-bcmath
      - php-curl
      - php-imagick
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
    become: yes