---
  - name: 'Installing packages'
    ansible.builtin.apt:
      state: latest
      update_cache: yes
      pkg:
      - mysql-server
      - python3-pymysql
    become: yes
  - name: 'Creating database'
    community.mysql.mysql_db:
      name: '{{ wordpress_db_name }}'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
    become: yes
  - name: 'Creating db wordpress user'
    community.mysql.mysql_user:
      name: '{{ wordpress_db_user }}'
      password: '{{ wordpress_db_password }}'
      priv: '{{ wordpress_db_name }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER'
      state: present
      login_unix_socket: /run/mysqld/mysqld.sock
      host: '{{ item }}'
    with_items:
    - 'localhost'
    - '127.0.0.1'
    - '{{ wordpress_host_ip }}'
    become: yes
  - name: 'Configure db'
    ansible.builtin.replace:
      path: '/etc/mysql/mysql.conf.d/mysqld.cnf'
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
    become: yes
    notify:
      - restart mysql